<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE eponyms [
	<!ELEMENT eponym (name, desc, cat*, c?, e?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT desc (#PCDATA)>
	<!ELEMENT cat (#PCDATA)>
	<!ELEMENT c (#PCDATA)>
	<!ELEMENT e (#PCDATA)>
]>
<root created="1218985136">
<eponym id="Abernethymalformation">
	<name>Abernethy malformation</name>
	<desc>congenital anomaly of the splanchnic vasculature, arises from defects in vitelline vein formation; in type 1, portal vein completely diverted into IVC and complete absence of formation of intrahepatic portal vein; in type 2, portal venous system is formed, but there is an abnormal communication with systemic veins, usually IVC; associated with hepatic encephalopathy and hepatopulmonary syndrome; more common in dogs, particularly Yorkshire terriers</desc>
	<cat>ANAT</cat>
	<cat>GI</cat>
	<c>01/17/05</c>
</eponym>
<eponym id="Achenbachssyndrome">
	<name>Achenbach’s syndrome</name>
	<desc>Rare entity of spontaneous or mechanically-induced hematomas on the volar aspect of fingers associated with burning pain and swelling of the digits</desc>
	<cat>SYND</cat>
	<cat>DERM</cat>
	<c>04/05/07</c>
</eponym>
<eponym id="Adamkiewiczarteryof">
	<name>Adamkiewicz, artery of</name>
	<desc>artery responsible for anterior spinal syndrome; can be severed in AAA repair</desc>
	<cat>ANAT</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Adamsonsfringe">
	<name>Adamson’s fringe</name>
	<desc>in tinea capitis, the location of the terminal tuft of hyphae; weakest point of hair located just about Adamson’s fringe</desc>
	<cat>DERM</cat>
	<cat>PATH</cat>
	<cat>ANAT</cat>
	<c>08/21/00</c>
</eponym>
<eponym id="Addisonsdisease">
	<name>Addison’s disease</name>
	<desc>primary adrenal insufficiency, bilateral adrenal destruction by TB used to be most common cause, now only accounts for 7-20% of cases; now autoimmune disease 70-90%, remainder caused by infectious disease, metastasis or lymphoma, adrenal hemorrhage, infarction, or drugs</desc>
	<cat>ENDO</cat>
	<c>08/21/00</c>
</eponym>
<eponym id="Adiespupil">
	<name>Adie’s pupil</name>
	<desc>tonic pupil, larger than contralateral unaffected pupil, reacts sluggishly to changes in illumination, see also Holmes-Adie syndrome; seen in young women; no neurologic significance</desc>
	<cat>OPHTH</cat>
	<cat>NEURO</cat>
	<c>03/21/98</c>
</eponym>
<eponym id="Adlersign">
	<name>Adler sign</name>
	<desc>for distinguishing appendicitis from adnexal or uterine pain, if the point of maximal tenderness shifts medially with repositioning on the left lateral side, etiology generally gynecologic</desc>
	<cat>GI</cat>
	<cat>SIGN</cat>
	<c>07/19/06</c>
</eponym>
<eponym id="Adsonssign">
	<name>Adson’s sign</name>
	<desc>in thoracic outlet syndrome, decrease in ipsilateral radial pulse and/or presence of subclavian bruit while patient extending neck maximally, rotating head towards side being tested, and holding breath</desc>
	<cat>ORTHO</cat>
	<cat>PROC</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="AhumadadelCastillosyndrome">
	<name>Ahumada-del Castillo syndrome</name>
	<desc>galactorrhea-amenorrhea not associated with pregnancy</desc>
	<cat>ENDO</cat>
	<cat>SYND</cat>
	<c>05/25/01</c>
</eponym>
<eponym id="Aicardisyndrome">
	<name>Aicardi syndrome</name>
	<desc>partial or complete agenesis of corpus callosum, infantile spasms, mental retardation, lacunae of the retina; occurs only in females; likely X-linked dominant with lethality in males; described in 1965</desc>
	<cat>NEURO</cat>
	<cat>OPHTH</cat>
	<cat>SYND</cat>
	<c>12/14/02</c>
</eponym>
<eponym id="ainhumdisease">
	<name>ainhum disease</name>
	<desc>autoamputation of a digit, usually of the fifth toe from a constricting scar in the form of a band or groove; usually from trauma acquired from walking barefoot; more common in tropics in patients of African descent; “ainhum” means “fissure” in one of the indigenous language in Brazil</desc>
	<cat>ORTHO</cat>
	<c>02/12/04</c>
</eponym>
<eponym id="Alagillesyndrome">
	<name>Alagille syndrome</name>
	<desc>inherited cholestatic syndrome, associated with biliary hypoplasia (ductopenia), vertebral anomalies, prominent forehead, deep-set eyes, peripheral pulmonic stenosis</desc>
	<cat>GI</cat>
	<cat>SYND</cat>
	<c>03/21/98</c>
</eponym>
<eponym id="AlbersSchnbergdisease">
	<name>Albers-Schönberg disease</name>
	<desc>osteopetrosis or marble bone disease</desc>
	<cat>ENDO</cat>
	<c>03/21/98</c>
</eponym>
<eponym id="Albertstest">
	<name>Albert’s test</name>
	<desc>for diagnosing hemineglect; patient presented with multiple lines on a page and asked to cross them out; if &gt;70% of crossed out lines are ipsilateral to motor deficit, hemineglect is diagnosed; described in Neurology 1973; 23:658-64</desc>
	<cat>NEURO</cat>
	<c>04/27/03</c>
	<e>6/2/2005</e>
</eponym>
<eponym id="Albrightshereditaryosteodystrophy">
	<name>Albright’s hereditary osteodystrophy</name>
	<desc>polyostotic fibrous dysplasia, short stature, round face, skeletal anomalies (brachydactyly, also see Archibald’s sign), and heterotopic calcification, precocious puberty, café-au-lait spots on skin, low calcium, high phosphate, resistance to elevated PTH levels from mutation in Gsalpha coupling PTH receptor to adenylyl cyclase</desc>
	<cat>ENDO</cat>
	<c>03/21/98</c>
</eponym>
<eponym id="AlderReillyanomaly">
	<name>Alder-Reilly anomaly</name>
	<desc>large, dark, pink-purple granules in cytoplasm of neutrophils; autosomal recessive trait resulting in abnormal granule development in neutrophils resembling severe toxic granulation</desc>
	<cat>HEME/ONC</cat>
	<c>03/21/98</c>
</eponym>
<eponym id="Alexandersdisease">
	<name>Alexander’s disease</name>
	<desc>leukodystrophy-like neurodegenerative disease presenting in infancy or childhood; characterized by Rosenthal fibers</desc>
	<cat>NEURO</cat>
	<cat>SYND</cat>
	<c>03/12/00</c>
</eponym>
<eponym id="Alexanderslaw">
	<name>Alexander’s law</name>
	<desc>peripheral vestibular nystagmus increases in intensity when the gaze is in the direction of the fast phase, and decreases in intensity when the gaze is away from the fast phase</desc>
	<cat>NEURO</cat>
	<cat>ENT</cat>
	<cat>SIGN</cat>
	<c>03/13/00</c>
</eponym>
<eponym id="Allenssign">
	<name>Allen’s sign</name>
	<desc>in pulmonary embolism, fever, tachycardia, and tachypnea, present in only 23% of cases</desc>
	<cat>PULM</cat>
	<cat>HEME/ONC</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Allenstest">
	<name>Allen’s test</name>
	<desc>for demonstrating patent ulnar artery and an intact superficial palmar arch, patient’s hand is initially held high while fist is clenched and both radial and ulnar arteries are compressed, hand then lowered and fist is opened; after ulnar pressure released, color should return to the hand within 6 seconds</desc>
	<cat>CV</cat>
	<cat>SIGN</cat>
	<cat>PROC</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Allissign">
	<name>Allis sign</name>
	<desc>in congenital hip dislocation, difference in knee height when child is supine with knees flexed and feet are flat on examination table</desc>
	<cat>SIGN</cat>
	<cat>ORTHO</cat>
	<c>10/12/03</c>
</eponym>
<eponym id="Alportssyndrome">
	<name>Alport’s syndrome</name>
	<desc>hereditary nephritis accompanied by deafness and various eye disorders, including lens dislocation, posterior cataracts, and corneal dystrophy; a few families have large platelets (20-25 fL), thrombocytopenia, and leukocyte inclusions which resemble May-Hegglin anomaly</desc>
	<cat>RENAL</cat>
	<cat>SYND</cat>
	<cat>HEME/ONC</cat>
	<c>06/02/00</c>
</eponym>
<eponym id="Alstrmssyndrome">
	<name>Alström’s syndrome</name>
	<desc>obesity, autosomal recessive, childhood blindness due to retinal degeneration, nerve deafness, vasopressin-resistant diabetes insipidus, and in males, hypogonadism with high plasma gonadotropin levels (end organ resistance to hormones), also baldness, hyperuricemia, hypertriglyceridemia, aminoaciduria</desc>
	<cat>ENDO</cat>
	<cat>SYND</cat>
	<c>04/13/00</c>
</eponym>
<eponym id="Alzheimersdisease">
	<name>Alzheimer’s disease</name>
	<desc>most frequent cause of dementia, pathologically characterized by neurofibrillary tangles, neuritic plaques, and granulovacuolar degeneration, degeneration of nucleus basalis of Meynert (principal origin of cholinergic innervation); described in 1906</desc>
	<cat>NEURO</cat>
	<c>03/08/00</c>
</eponym>
<eponym id="Amadoriproduct">
	<name>Amadori product</name>
	<desc>products of early non enzymatic glycosylation of proteins</desc>
	<cat>BIOCHEM</cat>
	<cat>ENDO</cat>
	<c>11/10/02</c>
</eponym>
<eponym id="Ambeshmaneuver">
	<name>Ambesh maneuver</name>
	<desc>Internal jugular vein occlusion test for diagnosis of misplaced subclavian vein catheter into the internal jugular vein.  Apply external pressure to the internal jugular vein and observe for change in central venous pressure and wave form.  Described in Anesthesiology 2001;95:1377</desc>
	<cat>PROC</cat>
	<c>08/07/08</c>
</eponym>
<eponym id="Amyandshernia">
	<name>Amyand’s hernia</name>
	<desc>perforated appendicitis contained within an incarcerated inguinal hernia (n.b. first appendectomy done by Claudius Amyand)</desc>
	<cat>PROC</cat>
	<cat>GI</cat>
	<c>07/21/08</c>
</eponym>
<eponym id="Andermannsyndrome">
	<name>Andermann syndrome</name>
	<desc>familial progressive sensorimotor neuropathy with agenesis of the corpus callosum, mental retardation; found in high frequency in Quebec; associated with mutation in SLC12A6, a K-Cl transporter</desc>
	<cat>NEURO</cat>
	<cat>SYND</cat>
	<c>10/18/03</c>
</eponym>
<eponym id="Andersendisease">
	<name>Andersen disease</name>
	<desc>type IV glycogen storage disease (or amylopectinosis), from branching enzyme deficiency, presents with cirrhosis with hepatosplenomegaly and failure to thrive in the first 18 months of life</desc>
	<cat>BIOCHEM</cat>
	<cat>SYND</cat>
	<c>04/27/01</c>
</eponym>
<eponym id="Andersenssyndrome">
	<name>Andersen’s syndrome</name>
	<desc>periodic muscle paralysis, arrhythmias, short stature, macrocephaly, hypertelorism, brachydactyly, tapering fingers; from mutation in KCNJ2 which encodes a potassium channel Kir2.1; also with dental abnormalities, incomplete secondary dentition, cleft palate, first described in 1971; also long QT syndrome 7 (LQT7)</desc>
	<cat>NEURO</cat>
	<cat>CV</cat>
	<c>07/02/01</c>
	<e>8/13/2005</e>
</eponym>
<eponym id="Angelssign">
	<name>Angel’s sign</name>
	<desc>performing an otoscopic exam while patient is blowing against a pinched nose; increases sensitivity of otoscopy for the detection of a perforated tympanic membrane by demonstrating fluid or pus in the external canal; described in 1994</desc>
	<cat>ENT</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Angelmansyndrome">
	<name>Angelman syndrome</name>
	<desc>“happy puppet” syndrome characterized by severe developmental delay, frequent laughing, easily excitable personality; from maternal deletion of 15q11-13; associated with mutation in maternally-imprinted ATP10C, a putative aminophospholipid translocase</desc>
	<cat>SYND</cat>
	<cat>BIOCHEM</cat>
	<c>05/27/01</c>
</eponym>
<eponym id="Anitschkowmyocytes">
	<name>Anitschkow myocytes</name>
	<desc>in rheumatic fever, large mesenchymal cells in myocardial lesion</desc>
	<cat>RHEUM</cat>
	<cat>CV</cat>
	<cat>PATH</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="AntleyBixlersyndrome">
	<name>Antley-Bixler syndrome</name>
	<desc>trapezoidocephaly-synostosis syndrome; characterized by midface hypoplasia, humeroradial synostosis, bowing of femora, fractures; associated with inactivating mutations in FGFR2; occasionally associated with ambiguous genitalia</desc>
	<cat>ORTHO</cat>
	<cat>SYND</cat>
	<c>07/05/04</c>
</eponym>
<eponym id="Antonssyndrome">
	<name>Anton’s syndrome</name>
	<desc>denial of cortical blindness; a form of anosognosia</desc>
	<cat>NEURO</cat>
	<cat>OPHTH</cat>
	<cat>SYND</cat>
	<c>03/04/00</c>
</eponym>
<eponym id="Apertsyndrome">
	<name>Apert syndrome</name>
	<desc>autosomal dominant disorder from mutation in FGFR2 characterized by craniosynostosis, mid-facial malformations, symmetric bony syndactyly of hands and feet, and varying degrees of mental retardation, from missense mutations in the fibroblast growth-factor-receptor 2 (FGFR2) genes</desc>
	<cat>ORTHO</cat>
	<cat>SYND</cat>
	<c>04/18/00</c>
</eponym>
<eponym id="Apgarscore">
	<name>Apgar score</name>
	<desc>developed in 1952, five parameters assessed:  heart rate, respiratory effort, muscle tone, reflex irritability, and color; score 7 or greater said to be indicator of good health; 5 minute score most reliable; 5 min score of 0-3, mortality 244/1000 v. score of 7-10, mortality 0.2/1000 (N Engl J Med 2001;344:467)</desc>
	<cat>SIGN</cat>
	<c>03/18/01</c>
</eponym>
<eponym id="Apleygrindtest">
	<name>Apley grind test</name>
	<desc>for meniscal tears, flex patient’s leg to 90 degrees, then grind the tibial condyles against the femoral condyles with rotation motion in the varus and then valgus positions</desc>
	<cat>ORTHO</cat>
	<cat>SIGN</cat>
	<cat>PROC</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Apleyscratchtest">
	<name>Apley scratch test</name>
	<desc>asking patient to scratch the back from above or bottom, looking for furthest point reached (T4-T5 former, T7-T8 latter normal); if can’t reach, infraspinatus/teres minor tendonitis tear or subscapularis tendonitis/tear respectively</desc>
	<cat>ORTHO</cat>
	<cat>SIGN</cat>
	<cat>PROC</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Apleyslaw">
	<name>Apley’s law</name>
	<desc>in pediatrics, the farther a chronically recurrent abdominal pain is from the umbilicus, the greater the likelihood of an organic cause for the pain</desc>
	<cat>GI</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Apttest">
	<name>Apt test</name>
	<desc>test which differentiates fetal from maternal hemoglobin in infant’s gastric contents, vomitus, or stool</desc>
	<cat>OB/GYN</cat>
	<cat>PATH</cat>
	<cat>HEME/ONC</cat>
	<c>02/28/00</c>
	<e>6/15/2002</e>
</eponym>
<eponym id="Archibaldssign">
	<name>Archibald’s sign</name>
	<desc>in pseudohypoparathyroidism of Albright’s hereditary osteodystrophy, characteristic shortening of the fourth and fifth digits as dimpling over the knuckles of a clenched fist</desc>
	<cat>ENDO</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
	<e>4/27/2003</e>
</eponym>
<eponym id="ArgyllRobertsonpupils">
	<name>Argyll Robertson pupils</name>
	<desc>small irregular pupils, usually but not always caused by CNS syphilis, they accommodate, but don’t react; absence of miotic reaction to light, both direct and consensual, with preservation of a miotic reaction to near stimulus; lesion in tectum of midbrain; named after Douglas M. C. L. Argyll Robertson.</desc>
	<cat>ID</cat>
	<cat>NEURO</cat>
	<cat>SIGN</cat>
	<cat>OPHTH</cat>
	<c>03/04/00</c>
</eponym>
<eponym id="Arnoldsnerve">
	<name>Arnold’s nerve</name>
	<desc>auricular branch of vagus nerve supplying posterior and inferior meatal skin of ear; stimulation can elicit cough reflex</desc>
	<cat>NEURO</cat>
	<cat>ENT</cat>
	<cat>ANAT</cat>
	<c>08/31/02</c>
</eponym>
<eponym id="Arnoldsreflex">
	<name>Arnold’s reflex</name>
	<desc>ear cough reflex mediated by Arnold’s nerve</desc>
	<cat>NEURO</cat>
	<cat>ENT</cat>
	<cat>ANAT</cat>
	<c>08/31/02</c>
</eponym>
<eponym id="ArnoldChiarimalformation">
	<name>Arnold-Chiari malformation</name>
	<desc>downward displacement of the cerebellar tonsils and medulla through the foramen magnum, results in pressure atrophy of displaced brain tissue, hydrocephalus from obstruction of the CSF outflow tract, is almost always characterized by the presence of a thoracolumbar meningomyelocele</desc>
	<cat>NEURO</cat>
	<cat>SYND</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Arthusreaction">
	<name>Arthus reaction</name>
	<desc>localized area of tissue necrosis resulting from acute immune complex vasculitis; type III hypersensitivity</desc>
	<cat>ID</cat>
	<cat>PATH</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Aschoffbody">
	<name>Aschoff body</name>
	<desc>pathognomonic finding in rheumatic carditis, an area of local fibrinoid necrosis surrounded by inflammatory cells including lymphocytes, plasma cells, and macrophages that later resolve to fibrous scar tissue</desc>
	<cat>CV</cat>
	<cat>SIGN</cat>
	<cat>PATH</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Ashermanssyndrome">
	<name>Asherman’s syndrome</name>
	<desc>intrauterine synechiae, typically occurs after curettage of the uterus, presenting as amenorrhea</desc>
	<cat>OB/GYN</cat>
	<cat>SYND</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Ashersonssyndrome">
	<name>Asherson’s syndrome</name>
	<desc>catastrophic antiphospholipid antibody syndrome</desc>
	<cat>RHEUM</cat>
	<c>12/07/05</c>
</eponym>
<eponym id="Ashmansphenomenon">
	<name>Ashman’s phenomenon</name>
	<desc>relationship of aberrancy to changes in the preceding cycle length; may persist for several cycles, usually exhibits RBBB morphology</desc>
	<cat>CV</cat>
	<c>01/21/01</c>
</eponym>
<eponym id="Askinstumor">
	<name>Askin’s tumor</name>
	<desc>malignant small-cell tumor of the thoracopulmonary region; member of Ewing sarcoma family or primitive neuroectodermal tumors</desc>
	<cat>HEME/ONC</cat>
	<c>08/13/05</c>
</eponym>
<eponym id="ASPENsyndrome">
	<name>ASPEN syndrome</name>
	<desc>Association of Sickle cell disease, Priapism (usually major), Exchange transfusion, Neurological events including headache, lethargy, and seizures; may be due to abrupt cerebral hypoxemia from too-rapid exchange or release of vasoactive cytokines released from penile blood vessels; described in J Urol. 1993; 150:1480-1482.</desc>
	<cat>NEURO</cat>
	<cat>URO</cat>
	<cat>HEME/ONC</cat>
	<c>06/30/02</c>
</eponym>
<eponym id="Aspergersdisorder">
	<name>Asperger’s disorder</name>
	<desc>severe and sustained impairment in social interactions and the development of restricted, repetitive patterns of behavior, interests, and activities, but intellectually normal and no language delays, but with abnormalities of spoken language</desc>
	<cat>PSYCH</cat>
	<cat>SYND</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Auenbruggerssign">
	<name>Auenbrugger’s sign</name>
	<desc>epigastric bulge due to a massive pericardial effusion</desc>
	<cat>GI</cat>
	<cat>CV</cat>
	<cat>SIGN</cat>
	<c>07/15/00</c>
</eponym>
<eponym id="Auerrods">
	<name>Auer rods</name>
	<desc>present in acute myelogenous leukemia or refractory anemia with excess blasts; granules form elongated needles, granules are all azurophilic, contain peroxidase; fused lysosomes</desc>
	<cat>HEME/ONC</cat>
	<cat>PATH</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Auerbachsplexus">
	<name>Auerbach’s plexus</name>
	<desc>myenteric plexus, between the longitudinal and circular layers of muscle; provides motor innervation to the two muscle layers and secretomotor innervation to the mucosa</desc>
	<cat>GI</cat>
	<cat>ANAT</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Auspitzssign">
	<name>Auspitz’s sign</name>
	<desc>for psoriasis; sign is positive when slight scratching or curetting of a scaly lesion reveals punctate bleeding points within the lesion; suggests psoriasis, but is not specific</desc>
	<cat>DERM</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="AustinFlintmurmur">
	<name>Austin Flint murmur</name>
	<desc>diastolic rumble in aortic regurgitation heard at cardiac apex, thought to be due to aortic jet impinging on the mitral valve, causing vibrations and also from simultaneous diastolic filling of the left ventricle from the left atrium and aorta closing the mitral valve in diastole, producing physiologic stenosis; named after Austin Flint (1812-1886)</desc>
	<cat>CV</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Australiaantigen">
	<name>Australia antigen</name>
	<desc>HBsAg, found in the serum of an Australian aborigine</desc>
	<cat>GI</cat>
	<cat>ID</cat>
	<cat>PATH</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Austriantriad">
	<name>Austrian triad</name>
	<desc>clinical triad of pneumococcal pneumonia, meningitis, and endocarditis (classically aortic valve endocarditis associated with aortic regurgitation); described by Robert Austrian</desc>
	<cat>ID</cat>
	<c>09/17/00</c>
	<e>5/25/2002</e>
</eponym>
<eponym id="Babinskisign">
	<name>Babinski sign</name>
	<desc>upper motor sign that indicates dysfunction of fibers within the pyramidal system; described in 1896 by Babinski, student of Charcot</desc>
	<cat>NEURO</cat>
	<cat>SIGN</cat>
	<cat>PROC</cat>
	<c>03/25/00</c>
</eponym>
<eponym id="Bachmannsbundle">
	<name>Bachmann’s bundle</name>
	<desc>anterior internodal tract in atrial conduction system</desc>
	<cat>CV</cat>
	<cat>ANAT</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Bainbridgereflex">
	<name>Bainbridge reflex</name>
	<desc>compensatory increase in heart rate caused by a rise in right atrial pressure</desc>
	<cat>CV</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Bakerscyst">
	<name>Baker’s cyst</name>
	<desc>popliteal cyst, a synovial cyst within the popliteal fossa</desc>
	<cat>RHEUM</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Balintssyndrome">
	<name>Balint’s syndrome</name>
	<desc>optic ataxia (inability to visually guide limb movements), ocular ataxia (inability to direct eyes to a precise point in the visual field), inability to enumerate objects in a picture or extract meaning from a picture, and inability to avoid objects in one’s path, simultanagnosia, from infarction in unilateral or bilateral visual association due to watershed stroke between distal PCA and MCA</desc>
	<cat>NEURO</cat>
	<cat>OPHTH</cat>
	<cat>SYND</cat>
	<c>03/06/00</c>
</eponym>
<eponym id="Balkannephropathy">
	<name>Balkan nephropathy</name>
	<desc>degenerative interstitial nephropathy seen in Balkan areas (tributaries of Danube River), with tubular proteinuria, glycosuria, RTA, azotemia, associated with increased risk of upper tract transitional cell carcinoma.  Hypothesized to be from chronic exposure to dietary aristolochic acid from Aristolochia clematitis, a plant native to endemic areas</desc>
	<cat>RENAL</cat>
	<cat>SYND</cat>
	<c>02/28/00</c>
	<e>7/13/2007</e>
</eponym>
<eponym id="Ballsdisease">
	<name>Ball’s disease</name>
	<desc>intracerebral leukocytostasis, potentially fatal complication of acute leukemia (especially AML) when peripheral blast cell count &gt;100,000/uL; leukemic cells capable of invading through endothelium and causing hemorrhage into brain; not generally seen with CLL or CML</desc>
	<cat>HEME/ONC</cat>
	<cat>NEURO</cat>
	<c>03/05/00</c>
</eponym>
<eponym id="Ballancessign">
	<name>Ballance’s sign</name>
	<desc>tender mass in the left upper quadrant due to a spleen hematoma</desc>
	<cat>GI</cat>
	<cat>SIGN</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Balsdisease">
	<name>Baló’s disease</name>
	<desc>variant of multiple sclerosis, see concentric rings of demyelination separated by bands of preserved myelin</desc>
	<cat>NEURO</cat>
	<c>08/08/01</c>
</eponym>
<eponym id="Balticmyoclonus">
	<name>Baltic myoclonus</name>
	<desc>see Unverricht-Lundborg disease</desc>
	<cat>NEURO</cat>
	<cat>SYND</cat>
	<c>09/02/02</c>
</eponym>
<eponym id="bamboospine">
	<name>bamboo spine</name>
	<desc>seen in ankylosing spondylitis</desc>
	<cat>SIGN</cat>
	<cat>RAYS</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Bancroftssign">
	<name>Bancroft’s sign</name>
	<desc>in deep vein thrombosis, compression of calf forward against tibia causing more pain than horizontal compression when gastrocnemius muscle is lifted; also referred to as Moses’s sign</desc>
	<cat>CV</cat>
	<cat>SIGN</cat>
	<cat>HEME/ONC</cat>
	<c>03/15/03</c>
</eponym>
<eponym id="Bangsdisease">
	<name>Bang’s disease</name>
	<desc>brucellosis</desc>
	<cat>ID</cat>
	<c>03/21/01</c>
</eponym>
<eponym id="BannayanRuvalcabaRileysyndrome">
	<name>Bannayan-Ruvalcaba-Riley syndrome</name>
	<desc>see Bannayan-Zonana syndrome</desc>
	<cat>NEURO</cat>
	<cat>HEME/ONC</cat>
	<c>03/04/03</c>
</eponym>
<eponym id="BannayanZonanasyndrome">
	<name>Bannayan-Zonana syndrome</name>
	<desc>hamartoma syndrome characterized by macrocephaly, multiple lipomas, and hemangiomas, speckled penis; associated with with germ line PTEN mutations; also known as Bannayan-Ruvalcaba-Riley syndrome </desc>
	<cat>NEURO</cat>
	<cat>DERM</cat>
	<cat>HEME/ONC</cat>
	<c>05/17/02</c>
	<e>3/3/2003</e>
</eponym>
<eponym id="Bannwarthssyndrome">
	<name>Bannwarth’s syndrome</name>
	<desc>in early disseminated Lyme disease, triad of lymphocytic meningitis, cranial nerve palsies (especially VII nerve which may be bilateral), and radiculoneuritis</desc>
	<cat>NEURO</cat>
	<cat>ID</cat>
	<cat>SYND</cat>
	<c>05/29/01</c>
</eponym>
<eponym id="Bantissyndrome">
	<name>Banti’s syndrome</name>
	<desc>splenomegaly, hypersplenism, and portal hypertension, noncirrhotic, arises after subclinical occlusion of the portal vein, usually years after occlusive event</desc>
	<cat>GI</cat>
	<cat>SYND</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Bantusiderosis">
	<name>Bantu siderosis</name>
	<desc>unusual form of iron overloading resembling hereditary hemochromatosis in South African blacks ingesting large quantities of alcoholic beverages fermented in iron utensils</desc>
	<cat>HEME/ONC</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Brnytest">
	<name>Bárány test</name>
	<desc>see Dix-Hallpike test</desc>
	<cat>NEURO</cat>
	<cat>SIGN</cat>
	<cat>PROC</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="BardetBiedlsyndrome">
	<name>Bardet-Biedl syndrome</name>
	<desc>mental retardation, pigmentary retinopathy, polydactyly, obesity, and hypogenitalism; genetically heterogeneous disorder with linkage to 7 loci; has been incorrectly called Laurence-Moon-Bardet-Biedl syndrome in the past</desc>
	<cat>ENDO</cat>
	<cat>SYND</cat>
	<c>03/18/03</c>
</eponym>
<eponym id="Barlowsdisease">
	<name>Barlow’s disease</name>
	<desc>mitral valve prolapse</desc>
	<cat>CV</cat>
	<c>08/09/00</c>
</eponym>
<eponym id="Barlowsmaneuver">
	<name>Barlow’s maneuver</name>
	<desc>for congenital hip dislocation, patient placed in supine position and attempt made to push femurs posteriorly with knees at 90 degrees/hip flexed and hip will dislocate</desc>
	<cat>ORTHO</cat>
	<cat>SIGN</cat>
	<cat>PROC</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Barrbody">
	<name>Barr body</name>
	<desc>condensed, inactive X-chromosome in females; dense, stainable structure</desc>
	<cat>PATH</cat>
	<c>03/26/05</c>
</eponym>
<eponym id="BarraquerSimonssyndrome">
	<name>Barraquer-Simons syndrome</name>
	<desc>acquired partial lipodystrophy; presents usually around 8-10, preceded generally by an acute viral infection; spares legs and hips; 1/3 of patients develop membranoproliferative glomerulonephritis; associated with accelerated complement activation and a serum immunoglobulin G, called C3 nephritic factor that are felt to cause lysis of adipose tissue</desc>
	<cat>ENDO</cat>
	<cat>RENAL</cat>
	<cat>SYND</cat>
	<c>05/13/01</c>
	<e>1/25/2004</e>
</eponym>
<eponym id="BarrLiousyndrome">
	<name>Barré-Liéou syndrome</name>
	<desc>cervicosympathetic syndrome, characterized  by neck pain and dizziness due to arthritic or traumatic damage to the cervical spine</desc>
	<cat>SYND</cat>
	<cat>NEURO</cat>
	<cat>ORTHO</cat>
	<c>06/30/04</c>
</eponym>
<eponym id="Barrettsesophagus">
	<name>Barrett’s esophagus</name>
	<desc>esophageal strictures and epithelial metaplasia from squamous epithelium to a specialized columnar epithelium with intestinal metaplasia in 10% of severe GERD</desc>
	<cat>GI</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Barthssyndrome">
	<name>Barth’s syndrome</name>
	<desc>infantile X-linked dilated cardiomyopathy, short stature, myopathy, cyclic neutropenia; from mutation in G4.5 which encodes for tafazzin (a putative acyl transferase that has been associated with altered metabolism of the mitochondrial phospholipid cardiolipin)</desc>
	<cat>NEURO</cat>
	<cat>CV</cat>
	<cat>SYND</cat>
	<c>07/07/01</c>
	<e>7/20/2006</e>
</eponym>
<eponym id="Bartholingland">
	<name>Bartholin gland</name>
	<desc>paired glands located near vaginal opening; maintain moisture of vaginal vestibular surfaces; can form abscesses or cysts; homologous to Cowper’s gland; described by Danish anatomist Caspar Bartholin in 1677</desc>
	<cat>OB/GYN</cat>
	<cat>ANAT</cat>
	<c>03/26/05</c>
</eponym>
<eponym id="Bartonsfracture">
	<name>Barton’s fracture</name>
	<desc>intra-articular fracture of dorsal margin of distal radius; extends into radio-carpal joint</desc>
	<cat>ORTHO</cat>
	<c>04/28/04</c>
</eponym>
<eponym id="Bartterssyndrome">
	<name>Bartter’s syndrome</name>
	<desc>hypokalemic, hypochloremic metabolic alkalosis with normal or low blood pressure despite increased renin and aldosterone levels and hyperplasia of juxtaglomerular apparatus due to mutations affecting diuretic-sensitive sodium-transport proteins</desc>
	<cat>RENAL</cat>
	<cat>SYND</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="BassenKornzweigsyndrome">
	<name>Bassen-Kornzweig syndrome</name>
	<desc>congenital abetalipoproteinemia</desc>
	<cat>SYND</cat>
	<cat>BIOCHEM</cat>
	<c>03/22/00</c>
</eponym>
<eponym id="batwingedema">
	<name>bat wing edema</name>
	<desc>pulmonary edema in perihilar distribution in approximately 5% of cases</desc>
	<cat>PULM</cat>
	<cat>CV</cat>
	<cat>SIGN</cat>
	<cat>RAYS</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Batemanssenilepurpura">
	<name>Bateman’s senile purpura</name>
	<desc>purpura following trauma to severely sun-damaged skin of the dorsal forearm of elderly persons; months may be required for resolution of pigmentation from hemorrhage</desc>
	<cat>DERM</cat>
	<c>02/28/00</c>
</eponym>
<eponym id="Batistaprocedure">
	<name>Batista procedure</name>
	<desc>for treatment of heart failure, removal of portion of left ventricular free wall, i.e. partial left ventriculectomy</desc>
	<cat>CV</cat>
	<c>08/25/01</c>
</eponym>
<eponym id="Batsonsplexus">
	<name>Batson's plexus</name>